### ISSUE TITLE
PHP Notice: Undefined index page.php on line 19

### ISSUE THREAD

**Issue by hubertbanas** [MichaelTunnell/las-picks#59]
Noticed the following in nginx logs 
```
2016/06/06 13:31:18 [error] 24860#0: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: distro in /var/www/www.jupiterbroadcasting.tk/html/laspicks/page.php on line 19
PHP message: PHP Notice:  Undefined index: distro in /var/www/www.jupiterbroadcasting.tk/html/laspicks/page.php on line 19
PHP message: PHP Notice:  Undefined index: distro in /var/www/www.jupiterbroadcasting.tk/html/laspicks/page.php on line 19
PHP message: PHP Notice:  Undefined index: distro in /var/www/www.jupiterbroadcasting.tk/html/laspicks/page.php on line 19
PHP message: PHP Notice:  Undefined index: distro in /var/www/www.jupiterbroadcasting.tk/html/laspicks/page.php on line 19
PHP message: PHP Notice:  Undefined index: distro in /var/www/www.jupiterbroadcasting.tk/html/laspicks/page.php on line 19
```

**Comment by MichaelTunnell** [comment]
That issue should not even be a problem, especially since nothing of the index has been altered since the last time to tested it.

I have made an adjustment to the index now though so test that.

**Comment by hubertbanas** [comment]
Still seeing the error.

**Comment by MichaelTunnell** [comment]
So I'm not sure why you are getting that error but it's isolated to your server.

[Live Server](http://www.jupiterbroadcasting.com/laspicks) = no error (updated to 420)

[MT Dev Server](http://michaeltunnell.com/jb/picks) = no error (updated to 420)

Since this error is not relevant to the repo itself or the data index, I'm closing the issue.
